### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by domybest123** [y9miao/VLSG#1]
During the environment installation process, some packages cannot be installed using pip. These packages seem to be related to ROS. How can I solve this problem?

**Comment by y9miao** [comment]
Thank you for your interest in our work. 
This problem is recently also reported by others and I will update the requirement file soon when getting time (should be done in August). Before that, an ugly solution is to neglect those ros-related depencies. The ros dependencies are installed for some extra experiments and it should be fine to neglect them.

**Comment by y9miao** [comment]
Hi, 
The requirement.txt is updated. It should work now.
